#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


rm -r postProcessing
foamListTimes -rm
rm -r signalFromStructSolver.dat
rm -r forcesplot.txt
rm -r *log*
rm -r 6DoF_1.dat

#------------------------------------------------------------------------------
